name: Blueprin / Provisioner demo
on: [push]
jobs:
  run-all: # TODO
    runs-on: ubuntu-latest
    environment: test-mmi
    env:
      ENV: dev 
      REGION: ap-southeast-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v2
        with:
          repository: qgervacio-dk/dk-aws-provisioner-storage
          path: .prov
          ref: main
      - uses: mikefarah/yq@master
      - uses: kishaningithub/setup-tf-summarize@v2
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7"
      - name: Testing required binaries
        run: |
          yq -V
          tf-summarize -v
          terraform -v
      - name: Running init, plan, apply and destroy
        run: |
          cp $ENV.terraform.tfvars.yaml .prov/
          cd .prov
          make i p a d workspace=$ENV
